"""Modelo del gestor centralizado de incidencias de Nexova: vocabulario, reglas y mapeo del CSV.

Contexto funcional: docs/centralized-incident-manager.md.
"""

from .csv_mapping import (
    CATEGORY_MAP,
    SEED_BRANCH,
    SEED_ORIGIN,
    STATUS_MAP,
    MappingIssue,
    RowIssue,
    SeedBatch,
    SeedIncident,
    derive_title,
    map_csv_row,
    parse_csv_date,
    prepare_seed_batch,
    source_key,
)
from .rules import (
    ALLOWED_TRANSITIONS,
    FILTER_FIELDS,
    FINAL_STATUSES,
    INITIAL_STATUS,
    INPUT_FIELDS,
    STATUS_CHANGE_FIELDS,
    FieldError,
    FieldErrorCode,
    IncidentDraft,
    IncidentFilters,
    IncidentValidationError,
    can_transition,
    check_transition,
    validate_filters,
    validate_incident_fields,
    validate_status_change,
)
from .vocabulary import BRANCH_LABELS, TITLE_MAX_LENGTH, Branch, IncidentCategory, IncidentOrigin, IncidentStatus

__all__ = [
    "ALLOWED_TRANSITIONS",
    "BRANCH_LABELS",
    "CATEGORY_MAP",
    "FILTER_FIELDS",
    "FINAL_STATUSES",
    "INITIAL_STATUS",
    "INPUT_FIELDS",
    "SEED_BRANCH",
    "SEED_ORIGIN",
    "STATUS_CHANGE_FIELDS",
    "STATUS_MAP",
    "TITLE_MAX_LENGTH",
    "Branch",
    "FieldError",
    "FieldErrorCode",
    "IncidentCategory",
    "IncidentDraft",
    "IncidentFilters",
    "IncidentOrigin",
    "IncidentStatus",
    "IncidentValidationError",
    "MappingIssue",
    "RowIssue",
    "SeedBatch",
    "SeedIncident",
    "can_transition",
    "check_transition",
    "derive_title",
    "map_csv_row",
    "parse_csv_date",
    "prepare_seed_batch",
    "source_key",
    "validate_filters",
    "validate_incident_fields",
    "validate_status_change",
]
